### PR TITLE
Updated code

### PR DESCRIPTION
**Pull request by calistus**
All Strings has been moved to string file.
unwanted files like 
.gradle, 
.idea
build/
and 
local.properties
has been removed

### CODE REVIEW

**Comment by rosariorobinson** [comment]
is this ready to go then?

**Comment by calistus** [comment]
I don't know why I can't see my code on GIthub after committing.
I am trying to work it out with Buddhi.

**Comment by sandarumk** [comment]
Ilo is this uptodate now? Did you commit your changes to your forked repository (aka calistus/pcsa)?

**Comment by calistus** [comment]
I have done that. The link below contains the complete code

https://github.com/systers/PCSA/pull/7

**Pull request merged**
